services:
  db:
    image: mariadb:latest
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./data/db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=medicareapp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin1234
    ports:
      - 3306:3306
volumes:
  db_data:
